version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Always increase the version requirement
    # to match the new version.
    versioning-strategy: increase
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
