#
# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -----------------------------------------------------------------------
# Kubernetes deployment for APIs.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portability
  name: portability-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portability
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portability
    spec:
      volumes:
      - name: portability-service-account-key
        secret:
          secretName: portability-service-account-creds
      containers:
      - name: portability-api
        image: IMAGE # Replaced by script
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: portability-service-account-key
          mountPath: /var/secrets/portability-service-account-key
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/portability-service-account-key/key.json
        - name: GOOGLE_PROJECT_ID
          value: PROJECT-ID # Replaced by script
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30