env: LOCAL
cloud: LOCAL
encryptedFlow: true
serviceProviderClasses: [
  "org.dataportabilityproject.serviceProviders.flickr.FlickrServiceProvider",
  "org.dataportabilityproject.serviceProviders.google.GoogleServiceProvider",
  "org.dataportabilityproject.serviceProviders.instagram.InstagramServiceProvider",
  "org.dataportabilityproject.serviceProviders.microsoft.MicrosoftServiceProvider",
  "org.dataportabilityproject.serviceProviders.rememberTheMilk.RememberTheMilkServiceProvider",
  "org.dataportabilityproject.serviceProviders.smugmug.SmugMugServiceProvider",
]